[package]
name = "wiki-generator"
version = "0.1.0"
authors = ["buttercrab <jaeyong0201@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
handlebars = "3"
pulldown-cmark = { version = "0.7", default-features = false }
regex = "1"
reqwest = { version = "0.10", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9.1"
toml = "0.5"
walkdir = "2"
